language: node_js
node_js:
  - "lts/carbon"
  - "lts/dubnium"
  - "10.15.0"
  - "node"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 'node'
    - node_js: 'lts/dubnium'
services:
  - docker
  - mongodb
addons:
  apt:
    sources:
    - mongodb-4.0-xenial
    packages:
    - mongodb-org-server
sudo: required
before_install:
  - export TZ=Africa/Johannesburg
after_success:
  - npm run coverage
  - ".travis/build_docker.sh"
notifications:
  slack:
    rooms:
      - jembihealthsystems:mlQYVFbijxcZkesCt7G5VBoM
    on_success: change
    on_failure: always
