language: node_js
dist: jammy
node_js:
  - "lts/fermium"
  - "lts/gallium"
  - "node"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 'node'
services:
  - mongodb
before_install:
  - export TZ=Africa/Johannesburg
script:
  - npm test
after_success:
  - npm run coverage
notifications:
  slack:
    rooms:
      - jembihealthsystems:mlQYVFbijxcZkesCt7G5VBoM
    on_success: change
    on_failure: always
